# for travis ci

sudo: required
services:
  - docker

before_install:
  - docker build -t jessiechenqazwsx/docker-react-learning -f Dockerfile.dev .
script:
  - docker run -e CI=true jessiechenqazwsx/docker-react-learning npm run test -- --coverage